### ISSUE TITLE
Does not scale to explicit size

### ISSUE THREAD

**Issue by nipponese** [marcisme/sketch-preview#22] opened 2015-06-03 17:53 UTC
Changing the "Scale to explicit size" setting plugin always exports as the same size.

I'm using Skala Preview 2 (205), and Skala View 1.8 on an iPhone 5s.

**Comment by marcisme** [comment] 2015-06-03 19:28
Thanks for reporting this issue.

Are you using Artboards? What are the dimensions of the Artboard in question? What are the dimensions of the exported preview image? Please also check the `Enable debug logging` option and paste the output from `Console.app` here.

**Comment by nipponese** [comment] 2015-06-04 23:46
Yes, tried using artboards and without. Also tried on a Nexus 6 and got same result. The copied items were from the iOS (iOS UI Design) and Android (Material Design) templates that ship with Sketch. Also, I was unable to find the `Enable debug logging` option.

**Comment by marcisme** [comment] 2015-06-04 23:58
If `Enable debug logging` isn't there, you probably have an old version of the plugin installed. I'd clean out any old versions from the plugin directory and install the latest version.

What was the size reported by `Skala Preview` in its main window? There should be dimensions right below the image. I'm wondering if they're exactly the same as the Artboard (most likely) or something else.

**Comment by marcisme** [comment] 2015-07-04 19:20
I still can't reproduce this, so I'm going to close this issue. Please re-open it if you'd like further assistance.

**Closed by marcisme** 2015-07-04 19:20 UTC
