### ISSUE TITLE
Support 3.3+?

### ISSUE THREAD

**Issue by jcwenzel** [marcisme/sketch-preview#21] opened 2015-05-12 14:08 UTC
First off this is an amazing tool. Thank you for creating it. I was wondering if you have any plans to support Sketch 3.3? Thanks!

**Comment by marcisme** [comment] 2015-05-12 16:48
Thanks. I'm glad you've found it useful.

I do plan to update to the new bundle format eventually, but for now the plugin is still working for me in 3.3.2. Is it not working for you? If not, what versions of Sketch, Skala Preview and the plugin are you using?

**Comment by jcwenzel** [comment] 2015-05-12 17:05
Awesome. I guess I might be having an issue with the WIFI connection
then... but just incase it is the plugin I'm using:

Skala Preview 1.6.0
Sketch 3.3.2
For the plugin I use Sketch Toolbox so it should be up-to-date

On Tue, May 12, 2015 at 9:48 AM, Marc Schwieterman <notifications@github.com

**Comment by marcisme** [comment] 2015-05-12 17:17
That should all work then. Is the file not opening in Skala Preview at all, or is it not showing up on your device? It might also be helpful to check for log messages in `Console.app`.

**Comment by ederdesign** [comment] 2015-05-14 01:56
Just wondering @marcisme. Did you manage to fix the problem? I'm actually having the same problem. I select the page, but nothing happens. I took a look at the console.app, but I have no idea about what's happening. Thanks.

**Comment by marcisme** [comment] 2015-05-14 02:00
@ederdesign Do you have an artboard selected? Also I've noticed that Sketch seems to need to be restarted after installation now before the keyboard shortcut works.

**Comment by Nordicdesign** [comment] 2015-05-30 16:00
I can't use it with 3.3.2, it doesn't load the preview on my machine, thus the phone doesn't know Skala Preview is running. I get the following message:
![screen shot 2015-05-30 at 16 55 02](https://cloud.githubusercontent.com/assets/4093514/7898090/fe78d308-06ec-11e5-8f2f-bfcf5548ae7b.png)

Also got a couple of warnings on the console, in case it's useful. No idea what all that means :)

30/05/2015 16:53:50.508 Sketch[7314]: Deprecation Warning in : /Users/alexlillo/Library/Application Support/com.bohemiancoding.sketch3/Plugins/SketchPreview/lib/common.js, line 21 «Plugin Developer»

30/05/2015 16:53:50.509 Sketch[7314]: Deprecation Warning in : /Users/alexlillo/Library/Application Support/com.bohemiancoding.sketch3/Plugins/SketchPreview/Preview.sketchplugin, line 23 «Plugin Developer»

30/05/2015 16:53:50.509 Sketch[7314]: Warning: #import syntax for CocoaScript is deprecated. Please update your script to use @import instead. «Plugin Developer»

**Comment by marcisme** [comment] 2015-05-30 17:48
@Nordicdesign Thanks for reporting this. Can you set the `DEBUG` variable to `true` in *SketchPreview/lib/common.js*, and post the output here? I still can't reproduce any problems on my machine, and the debug output will give me some more information to work with.

**Comment by marcisme** [comment] 2015-05-30 20:41
@Nordicdesign Did you happen to rename `Skala Preview` to something else?

**Comment by marcisme** [comment] 2015-05-31 01:43
I updated the plugin to `v0.8.0` today, and it is now using the new bundle format. I also moved the debug logging into the setup plugin, so turning that on no longer requires editing a file. Give the new version a try, and let me know if it's still not working for you.

**Comment by Nordicdesign** [comment] 2015-05-31 19:06
Still nothing I'm afraid.

I've deleted the plugin and installed it again, just in case. The funny
thing is that the setup screen works.
I tried with a brand new file, and still nothing. Also disabled the
firewall just in case.

This is what I got on the console app, in case it helps.

Thanks

**Comment by marcisme** [comment] 2015-05-31 19:22
Does `Skala Preview` work on its own? For example, if you drag and drop an image onto its dock icon, does that image show up in the main application window?

Are you using the direct download version of Sketch? (I'd guess so based on the preview image path.) I'll see if I can reproduce with the demo version.

**Comment by Nordicdesign** [comment] 2015-05-31 19:29
Ok you can close it now. This SO terribly embarrassing that I'd prefer not to say why it wasn't working but... here you go:

I didn't have Skala Preview installed in this machine.

Stupid, I now. I did a fresh install some days ago, and what I remembered was the sketch plugin, not the app itself. So I installed the plugin and thought that it was enough, and went to install all the other software. Sketch said 'make sure Skala Preview is installed' and I thought it was... the plugin of course, not the app. ARRGGG, idiot. 

Anyway, really sorry about this, and thanks for the help :S  You can have a laugh on me. :)

**Comment by marcisme** [comment] 2015-05-31 19:32
Believe me, stuff like that happens to all of us. ;) I'm glad it's working for you now.

**Closed by marcisme** 2015-05-31 19:32 UTC
