### ISSUE TITLE
Bitmap Exporting and Importing compatibility with macOS High Sierra

### ISSUE THREAD

**Issue by richardsison** [marcisme/sketch-preview#46] opened 2018-04-06 01:31 UTC
Since Sketch 49 (up until 49.2), there's been an odd colour conversion issue. This is what would happen: https://d.pr/i/Mwigd

Last night, Sketch updated to 49.3 and [fixed this bug.](https://www.sketchapp.com/updates/)

Unfortunately, the issue still occurs with Skala Preview. See example: https://d.pr/i/icetna

When I drag images directly onto Skala it's correct, but when the Sketch Preview pushes the artboard to Skala Preview, the colours are still incorrect.

Have you run into this? …Hopefully this makes sense…!

**Comment by marcisme** [comment] 2018-04-07 15:48
@richardsison Thanks for reporting this. I can reproduce it, and I'm currently investigating.

**Comment by marcisme** [comment] 2018-04-07 18:10
@richardsison I think this has something to do with the color profile. If I change the document color profile to P3, then the exported images look correct when exported to Skala Preview. Prior to changing anything, the test document I'm using was "Unmanaged".

I'm using an older export mechanism in the plugin, which seems to not embed a color profile. There seems to be a newer mechanism used by the official Javascript API for Sketch that does embed a profile, but I still can't get the colors right without changing the document to P3.

This is going to require some additional research.

**Comment by marcisme** [comment] 2018-04-07 18:11
Note that drag and dropping an dartboard to Skala Preview looks correct in all cases, but I've yet to figure out how to analyze the drag and drop data to see what exactly it contains.

**Comment by richardsison** [comment] 2018-04-09 01:31
You sir are a legend. Thanks so much for getting back to me!

Unfortunately not even changing to P3 fixes it for me. The [colours are all over the place](https://d.pr/i/sIAl9j). Only manually dragging an artboard works.

Fingers crossed! Hope this gets fixed soon. Thanks mate!

This plugin has been such a solid little plugin for ages. I've been using the Sketch Preview > Skala Preview > Skala View combo for mirroring for years. It's always been more reliable than Sketch's built-in solution. This has been the only time I've had an issue!

Sketch 49 has also introduced some bug which affects auto-updating plugins. Seems to happen when I open a second Sketch file (i.e. library or just new file) the auto-update required for Sketch Preview (and the Paddy plugin) stops working. It requires a Sketch restart to fix it.

Anyway, keep up the awesome work!

**Comment by marcisme** [comment] 2018-04-10 17:49
@richardsison I'm sorry to hear P3 didn't work for you. I'm not sure how realistic of a workaround that would be for most people anyways. I'm still looking into this.

Regarding the auto update, that may be related to one of the settings the plugin uses to stay in memory. At some point in the past there was a leak issue with too many versions of the plugin getting loaded, which that setting fixed. I may be able to remove that now, but I consider it a much lower priority issue in comparison to this color one.

**Comment by Rusik** [comment] 2018-04-17 11:12
Also found this issue :'(

**Comment by marcisme** [comment] 2018-04-17 16:29
@Rusik @mjboswell I'm sorry this is affecting both of you.

I think this may be a bug with how `NSImage` renders images it determines to be sRGB. I might have a workaround, but I'm still assessing its impacts and how feasible it will be to do through Cocoascript.

**Comment by marcisme** [comment] 2018-04-17 16:35
I may have actually just found a simple fix. The current problem is related to the PNG format, and I think exporting as TIFF may be an option.

**Comment by marcisme** [comment] 2018-04-17 16:54
@Rusik @mjboswell @richardsison I still need to do some testing, but this may work for you for now.

``` bash
cd /tmp
git clone https://github.com/marcisme/sketch-preview.git
cd sketch-preview/
git checkout color-fix
open SketchPreview.sketchplugin
```

Then restart Sketch.

If you try the above, let me know if it works for you.

**Comment by mjboswell** [comment] 2018-04-17 16:57
@marcisme – You sir are a gentleman and a scholar!

**Comment by richardsison** [comment] 2018-04-17 23:32
@marcisme Dammit… Still not working for me. [Updated Sketch Preview as per above](https://d.pr/i/akdxXc), checked colour settings that they're on P3 (also tried sRGB again…) but still getting same issue: https://d.pr/i/0alh5F

**Comment by richardsison** [comment] 2018-04-18 00:41
@marcisme !!! [Unchecking "Save for Web" worked](https://d.pr/i/Ah66S2)! 

Thank you so much for getting onto that so promptly… Now I can get back to work properly haha

You are a legend.

Cheers,
Rich

**Comment by marcisme** [comment] 2018-04-18 00:55
@richardsison Awesome! I'll update the plugin to set that option to false, so it won't be affected by the current default.

Thank you for helping figure this out.

**Comment by richardsison** [comment] 2018-04-18 10:09
No problem at all. It was all you!

Cheers,
Rich

**Comment by marcisme** [comment] 2018-04-19 20:15
This should be fixed in `v0.13.0`, released now.

Thanks again for the reports.

**Closed by marcisme** 2018-04-19 20:15 UTC

**Comment by mjboswell** [comment] 2018-04-19 21:06
Awesome work, @marcisme! Is there anything I need to run in Terminal now, or will the update just overwrite the temporary fix you had me do?

**Comment by marcisme** [comment] 2018-04-19 21:17
@mjboswell Thanks! Sketch should notice the plugin has a new version available eventually, and it should overwrite the temporary version when you update.
